<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Array con los datos de los países
        $countries = [
            [2, "Afghanistan"],
            [3, "Albania"],
            [4, "Algeria"],
            [5, "Andorra"],
            [6, "Angola"],
            [7, "Antigua and Barbuda"],
            [8, "Argentina"],
            [9, "Armenia"],
            [10, "Australia"],
            [11, "Austria"],
            [12, "Azerbaijan"],
            [13, "Bahamas"],
            [14, "Bahrain"],
            [15, "Bangladesh"],
            [16, "Barbados"],
            [17, "Belarus"],
            [18, "Belgium"],
            [19, "Belize"],
            [20, "Benin"],
            [21, "Bhutan"],
            [23, "Bosnia"],
            [24, "Botswana"],
            [25, "Brazil"],
            [26, "Brunei"],
            [27, "Bulgaria"],
            [28, "Burkina Faso"],
            [29, "Burundi"],
            [30, "Cambodia"],
            [31, "Cameroon"],
            [32, "Canada"],
            [33, "Cape Verde"],
            [34, "Central African Republic"],
            [35, "Chad"],
            [36, "Chile"],
            [37, "China"],
            [38, "Colombia"],
            [39, "Comoros"],
            [40, "Congo"],
            [41, "DR of Congo"],
            [42, "Costa Rica"],
            [43, "Ivory Coast"],
            [44, "Croatia"],
            [45, "Cuba"],
            [46, "Cyprus"],
            [47, "Czech Republic"],
            [48, "Denmark"],
            [49, "Djibouti"],
            [50, "Dominica"],
            [51, "Dominican Republic"],
            [52, "East Timor"],
            [53, "Ecuador"],
            [54, "Egypt"],
            [55, "El Salvador"],
            [56, "Equatorial Guinea"],
            [57, "Eritrea"],
            [58, "Estonia"],
            [59, "Ethiopia"],
            [60, "Fiji"],
            [61, "Finland"],
            [62, "France"],
            [63, "Gabon"],
            [64, "Gambia"],
            [65, "Georgia"],
            [66, "Germany"],
            [67, "Ghana"],
            [68, "Greece"],
            [69, "Grenada"],
            [70, "Guatemala"],
            [71, "Guinea"],
            [72, "Guinea-Bissau"],
            [73, "Guyana"],
            [74, "Haiti"],
            [75, "Honduras"],
            [76, "Hungary"],
            [77, "Iceland"],
            [78, "India"],
            [79, "Indonesia"],
            [80, "Iran"],
            [81, "Iraq"],
            [82, "Ireland"],
            [83, "Israel"],
            [84, "Italy"],
            [85, "Jamaica"],
            [86, "Japan"],
            [87, "Jordan"],
            [88, "Kazakhstan"],
            [89, "Kenya"],
            [91, "North Korea"],
            [92, "South Korea"],
            [93, "Kuwait"],
            [94, "Kyrgyzstan"],
            [95, "Laos"],
            [96, "Latvia"],
            [97, "Lebanon"],
            [98, "Lesotho"],
            [99, "Liberia"],
            [100, "Libya"],
            [101, "Liechtenstein"],
            [102, "Lithuania"],
            [103, "Luxembourg"],
            [104, "Macedonia"],
            [105, "Madagascar"],
            [106, "Malawi"],
            [107, "Malaysia"],
            [108, "Maldives"],
            [109, "Mali"],
            [111, "Mauritania"],
            [112, "Mauritius"],
            [113, "Mexico"],
            [114, "Micronesia"],
            [115, "Moldova"],
            [116, "Monaco"],
            [118, "Mongolia"],
            [119, "Morocco"],
            [120, "Mozambique"],
            [121, "Myanmar (Burma)"],
            [122, "Namibia"],
            [123, "Nauru"],
            [124, "Nepal"],
            [126, "New Zealand"],
            [127, "Nicaragua"],
            [128, "Niger"],
            [129, "Nigeria"],
            [130, "Norway"],
            [131, "Oman"],
            [132, "Pakistan"],
            [134, "Panama"],
            [135, "Papua New Guinea"],
            [136, "Paraguay"],
            [137, "Peru"],
            [138, "Philippines"],
            [139, "Poland"],
            [140, "Portugal"],
            [141, "Qatar"],
            [143, "Russia"],
            [144, "Rwanda"],
            [145, "Saint Kitts and Nevis"],
            [146, "Saint Lucia"],
            [147, "Saint Vincent and the Grenadines"],
            [148, "Samoa"],
            [149, "San Marino"],
            [150, "Sao Tome and Principe"],
            [151, "Saudi Arabia"],
            [152, "Senegal"],
            [153, "Serbia"],
            [154, "Seychelles"],
            [156, "Singapore"],
            [157, "Slovakia"],
            [158, "Slovenia"],
            [160, "Somalia"],
            [161, "South Africa"],
            [162, "Spain"],
            [163, "Sri Lanka"],
            [164, "Sudan"],
            [166, "Swaziland"],
            [167, "Sweden"],
            [168, "Switzerland"],
            [169, "Syria"],
            [170, "Taiwan"],
            [171, "Tajikistan"],
            [172, "Tanzania"],
            [173, "Thailand"],
            [174, "Togo"],
            [175, "Tonga"],
            [176, "Trinidad and Tobago"],
            [177, "Tunisia"],
            [178, "Turkey"],
            [179, "Turkmenistan"],
            [181, "Uganda"],
            [182, "Ukraine"],
            [183, "United Arab Emirates"],
            [185, "United States"],
            [186, "Uruguay"],
            [187, "Uzbekistan"],
            [188, "Vanuatu"],
            [189, "Vatican City (Holy See)"],
            [190, "Venezuela"],
            [191, "Vietnam"],
            [192, "Yemen"],
            [193, "Zambia"],
            [194, "Zimbabwe"],
            [196, "Netherlands"],
            [209, "Bolivia"],
            [210, "Malta"],
            [214, "England"],
            [216, "Scotland"],
            [217, "Wales"],
            [218, "New Caledonia"],
            [219, "Solomon Islands"],
            [220, "Guam"],
            [221, "French Polynesia"],
            [222, "American Samoa"],
            [223, "Sierra Leone"],
            [224, "Western Sahara"],
            [225, "Palestinian Territory"],
            [226, "Bermuda"],
            [227, "Greenland"],
            [228, "Saint Pierre and Miquelon"],
            [229, "Anguilla"],
            [230, "Aruba"],
            [231, "Cayman Islands"],
            [232, "Guadeloupe"],
            [233, "Martinique"],
            [234, "Montserrat"],
            [235, "Puerto Rico"],
            [236, "Turks and Caicos Islands"],
            [237, "Virgin Islands, U.S."],
            [238, "Romania"],
            [240, "Faroe Islands"],
            [241, "Guernsey"],
            [242, "Jersey"],
            [243, "Isle of Man"],
            [244, "Svalbard"],
            [245, "Gibraltar"],
            [246, "Falkland Islands"],
            [288, "Northern Ireland"],
            [289, "Virgin Island, British"],
            [290, "Reunion"],
            [291, "Borneo"],
            [293, "Suriname"],
            [294, "Cook Islands"],
            [295, "Montenegro"],
            [297, "Kosovo"],
            [299, "St Martin"],
            [300, "Curaçao"],
            [301, "Hong Kong"],
            [302, "Macau"],
            [303, "Bora Bora"],
            [304, "Antarctica"]
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                't_country_id' => $country[0],
                'name' => $country[1],
            ]);
        }
    }
}
