stages:
  - builder
  - deploy

Builder:
  stage: builder
  image: docker:20.10.16

  services:
    - name: docker:dind
      alias: dind
  variables:
    DOCKER_HOST: tcp://dind:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_IMAGE_REGISTRY: $CI_REGISTRY/$CI_PROJECT_PATH
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "$CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - echo "$DB_CONNECTION $DB_HOST $DB_PORT $DB_DATABASE $DB_USERNAME $DB_PASSWORD"
    # - docker build -t $DOCKER_IMAGE_REGISTRY:1.0.0 -f Dockerfile-build --build-arg DB_CONNECTION=$DB_CONNECTION --build-arg DB_HOST=$DB_HOST --build-arg DB_PORT=$DB_PORT --build-arg DB_DATABASE=$DB_DATABASE --build-arg DB_USERNAME=$DB_USERNAME --build-arg DB_PASSWORD=$DB_PASSWORD .
    - docker build -t $DOCKER_IMAGE_REGISTRY:1.0.0 -f Dockerfile-build .
    - docker push $DOCKER_IMAGE_REGISTRY:1.0.0
  only:
    - develop

Deployment:
  stage: deploy
  image: docker:20.10.16

  services:
    - name: docker:dind
      alias: dind
  variables:
    DOCKER_HOST: tcp://dind:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_IMAGE_REGISTRY: $CI_REGISTRY/$CI_PROJECT_PATH
  script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - ssh-keyscan "$SSH_HOST" >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER"@"$SSH_HOST" rm -rf api/
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER"@"$SSH_HOST" git clone https://api:glpat-fMzcQdp8xN4LXWr_TxfB@gitlab.com/antoniovibeadventures/api.git
    - ssh -o StrictHostKeyChecking=no "$USER"@"$SSH_HOST" "echo '$CI_REGISTRY_PASSWORD' | docker login -u '$CI_REGISTRY_USER' --password-stdin '$CI_REGISTRY' && docker pull '$DOCKER_IMAGE_REGISTRY:1.0.0'"
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER"@"$SSH_HOST" "cd /home/ubuntu/api && docker compose down"
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER"@"$SSH_HOST" "docker image inspect nginx:latest >/dev/null 2>&1 && docker image rm nginx:latest || echo 'La imagen nginx:latest no existe'"
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER"@"$SSH_HOST" "docker image inspect node:20.5.1-alpine >/dev/null 2>&1 && docker image rm node:20.5.1-alpine || echo 'La imagen node:20.5.1-alpine no existe'"
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER"@"$SSH_HOST" "docker image inspect registry.gitlab.com/antoniovibeadventures/api:1.0.0 >/dev/null 2>&1 && docker image rm registry.gitlab.com/antoniovibeadventures/api:1.0.0 || echo 'La imagen registry.gitlab.com/antoniovibeadventures/api:1.0.0 no existe'"
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER"@"$SSH_HOST" "cd /home/ubuntu/api && docker compose up -d --build"

  only:
    - develop
