FROM php:8.3-fpm

# Install required dependencies and PHP extensions
RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    unzip \
    mariadb-client \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql zip

WORKDIR /var/www/html

# Copy app code into the container
COPY . .

# Copy composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Install PHP dependencies
RUN composer update
RUN composer install --no-dev --optimize-autoloader --working-dir=/var/www/html

# Set proper file permissions
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && \
    chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

# Start PHP-FPM (this is handled by the base image, so no need for `php-fpm` here)
CMD ["php-fpm"]
