FROM php:8.3

RUN apt-get update && \
    apt-get install -y \
    cron \
    supervisor \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    unzip \
    mariadb-client \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql zip


COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .


COPY ./docker/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./docker/cron/schedule-cron /etc/cron.d/schedule-cron


# Ajustar permisos
RUN chmod 0644 /etc/cron.d/schedule-cron && \
    crontab /etc/cron.d/schedule-cron


RUN composer update

RUN composer install --no-dev --optimize-autoloader --working-dir=/var/www/html

RUN php artisan key:generate && \
    php artisan optimize

RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && \
    chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache


    CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# From selecciona la version php 8.3 con la que se desea trabajar
# Run indica las biblotecas requeridas para la instalacion (manejo de imagenes, controlador de bd,etc)
# Copy para copiar composer desde su imagen oficial. Esto es para asegurar que se tenga la ultima version siempre disponible
# Workdir indica el lugar donde se ejecutara la aplicacion
# el primer Run ejecuta un composer update, el segundo Run ejecuta la instalacion de dependencias para produccion. el terceo
#ejecuta comando de laravel para poder usar la aplicacion y el cuarto para otorgar permisos necesarios para almacenamiento (lectura y escritura)

