FROM nginx:latest

WORKDIR /var/www/html

COPY ./default.conf /etc/nginx/conf.d/default.conf

COPY . .

RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && \
    chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache


